export const defaultConfig = {
    "midi_note_1": -1,
    "midi_note_2": -1,
    "midi_note_3": -1,
    "midi_note_4": -1,
    "midi_note_5": -1,
    "midi_note_6": -1,
    "midi_note_7": -1,
    "midi_note_8": -1,
    "midi_note_9": -1,
    "midi_note_10": -1,
    "midi_note_11": -1,
    "midi_note_12": -1,
    "midi_note_13": -1,
    "midi_note_14": -1,
    "midi_note_15": -1,
    "midi_note_16": -1,
    "midi_note_sound": -1,
    "midi_note_pattern": -1,
    "midi_note_bpm": -1,
    "midi_note_special": -1,
    "midi_note_fx": -1,
    "midi_note_play": -1,
    "midi_note_write": -1,
    "po_midi_channel": 1,
    "synth_midi_channel": 1,
    "disable_transport": 0,
    "po_cc_control": 0,
    "volca_fm_velocity": 0,
    "volca_fm_midi_ch_1": 3,
    "volca_fm_midi_ch_2": 4,
    "sync_out_enabled": 0,
    "synth_enabled": 0,
    "midi_ppqn": 24,
    "midi_note_record_1": -1,
    "midi_note_record_2": -1,
    "midi_note_record_3": -1,
    "midi_note_record_4": -1,
    "midi_note_record_5": -1,
    "midi_note_record_6": -1,
    "midi_note_record_7": -1,
    "midi_note_record_8": -1,
    "midi_note_record_9": -1,
    "midi_note_record_10": -1,
    "midi_note_record_11": -1,
    "midi_note_record_12": -1,
    "midi_note_record_13": -1,
    "midi_note_record_14": -1,
    "midi_note_record_15": -1,
    "midi_note_record_16": -1,
    "looper_enabled": 0,
    "looper_autoplay_after_record": 0,
    "looper_transport_control_link": 0,
    "midi_note_loop_start_stop": 0,
    "midi_note_loop_clear": 0,
    "looper_quantized": 0,
    "ble_midi_enabled": 0
  }


export const eepromAddresses: { [key: string]: number } ={
  "midi_note_1": 1,
  "midi_note_2": 2,
  "midi_note_3": 3,
  "midi_note_4": 4,
  "midi_note_5": 5,
  "midi_note_6": 6,
  "midi_note_7": 7,
  "midi_note_8": 8,
  "midi_note_9": 9,
  "midi_note_10": 10,
  "midi_note_11": 11,
  "midi_note_12": 12,
  "midi_note_13": 13,
  "midi_note_14": 14,
  "midi_note_15": 15,
  "midi_note_16": 16,
  "midi_note_sound": 17,
  "midi_note_pattern": 18,
  "midi_note_bpm": 19,
  "midi_note_special": 20,
  "midi_note_fx": 21,
  "midi_note_play": 22,
  "midi_note_write": 23,
  "po_midi_channel": 24,
  "disable_transport": 26,
  "po_cc_control": 27,
  "volca_fm_velocity": 28,
  "volca_fm_midi_ch_1": 29,
  "volca_fm_midi_ch_2": 30,
  "sync_out_enabled": 31,
  "midi_ppqn": 33,
  "midi_note_record_1": 34,
  "midi_note_record_2": 35,
  "midi_note_record_3": 36,
  "midi_note_record_4": 37,
  "midi_note_record_5": 38,
  "midi_note_record_6": 39,
  "midi_note_record_7": 40,
  "midi_note_record_8": 41,
  "midi_note_record_9": 42,
  "midi_note_record_10": 43,
  "midi_note_record_11": 44,
  "midi_note_record_12": 45,
  "midi_note_record_13": 46,
  "midi_note_record_14": 47,
  "midi_note_record_15": 48,
  "midi_note_record_16": 49,
  "looper_enabled": 50,
  "looper_autoplay_after_record": 51,
  "looper_transport_control_link": 52,
  "midi_note_loop_start_stop": 53,
  "midi_note_loop_clear": 54,
  "looper_quantized": 55,
  "ble_midi_enabled": 56
}

  export interface configInterface {
    "midi_note_1": number;
    "midi_note_2": number;
    "midi_note_3": number;
    "midi_note_4": number;
    "midi_note_5": number;
    "midi_note_6": number;
    "midi_note_7": number;
    "midi_note_8": number;
    "midi_note_9": number;
    "midi_note_10": number;
    "midi_note_11": number;
    "midi_note_12": number;
    "midi_note_13": number;
    "midi_note_14": number;
    "midi_note_15": number;
    "midi_note_16": number;
    "midi_note_sound": number;
    "midi_note_pattern": number;
    "midi_note_bpm": number;
    "midi_note_special": number;
    "midi_note_fx": number;
    "midi_note_play": number;
    "midi_note_write": number;
    "po_midi_channel": number;
    "disable_transport": number;
    "po_cc_control": number;
    "volca_fm_velocity": number;
    "volca_fm_midi_ch_1": number;
    "volca_fm_midi_ch_2": number;
    "sync_out_enabled": number;
    "midi_ppqn": number;
    "midi_note_record_1": number;
    "midi_note_record_2": number;
    "midi_note_record_3": number;
    "midi_note_record_4": number;
    "midi_note_record_5": number;
    "midi_note_record_6": number;
    "midi_note_record_7": number;
    "midi_note_record_8": number;
    "midi_note_record_9": number;
    "midi_note_record_10": number;
    "midi_note_record_11": number;
    "midi_note_record_12": number;
    "midi_note_record_13": number;
    "midi_note_record_14": number;
    "midi_note_record_15": number;
    "midi_note_record_16": number;
    "looper_enabled": number;
    "looper_autoplay_after_record": number;
    "looper_transport_control_link": number;
    "midi_note_loop_start_stop": number;
    "midi_note_loop_clear": number;
    "looper_quantized": number;
    "ble_midi_enabled": number;
}