export const defaultConfig = {
    "midi_note_1": 255,
    "midi_note_2": 255,
    "midi_note_3": 255,
    "midi_note_4": 255,
    "midi_note_5": 255,
    "midi_note_6": 255,
    "midi_note_7": 255,
    "midi_note_8": 255,
    "midi_note_9": 255,
    "midi_note_10": 255,
    "midi_note_11": 255,
    "midi_note_12": 255,
    "midi_note_13": 255,
    "midi_note_14": 255,
    "midi_note_15": 255,
    "midi_note_16": 255,
    "midi_note_sound": 255,
    "midi_note_pattern": 255,
    "midi_note_bpm": 255,
    "midi_note_special": 255,
    "midi_note_fx": 255,
    "midi_note_play": 255,
    "midi_note_write": 255,
    "po_midi_channel": 1,
    "synth_midi_channel": 1,
    "disable_transport": 0,
    "po_cc_control": 0,
    "volca_fm_velocity": 0,
    "volca_fm_midi_ch_1": 3,
    "volca_fm_midi_ch_2": 4,
    "sync_out_enabled": 0,
    "synth_enabled": 0,
    "midi_ppqn": 24,
    "midi_note_record_1": 255,
    "midi_note_record_2": 255,
    "midi_note_record_3": 255,
    "midi_note_record_4": 255,
    "midi_note_record_5": 255,
    "midi_note_record_6": 255,
    "midi_note_record_7": 255,
    "midi_note_record_8": 255,
    "midi_note_record_9": 255,
    "midi_note_record_10": 255,
    "midi_note_record_11": 255,
    "midi_note_record_12": 255,
    "midi_note_record_13": 255,
    "midi_note_record_14": 255,
    "midi_note_record_15": 255,
    "midi_note_record_16": 255,
    "looper_enabled": 0,
    "looper_autoplay_after_record": 0,
    "looper_transport_control_link": 0,
    "midi_note_loop_start_stop": 0,
    "midi_note_loop_clear": 0,
    "looper_quantized": 0,
    "ble_midi_enabled": 0
  }
  export interface configInterface {
    "midi_note_1": number;
    "midi_note_2": number;
    "midi_note_3": number;
    "midi_note_4": number;
    "midi_note_5": number;
    "midi_note_6": number;
    "midi_note_7": number;
    "midi_note_8": number;
    "midi_note_9": number;
    "midi_note_10": number;
    "midi_note_11": number;
    "midi_note_12": number;
    "midi_note_13": number;
    "midi_note_14": number;
    "midi_note_15": number;
    "midi_note_16": number;
    "midi_note_sound": number;
    "midi_note_pattern": number;
    "midi_note_bpm": number;
    "midi_note_special": number;
    "midi_note_fx": number;
    "midi_note_play": number;
    "midi_note_write": number;
    "po_midi_channel": number;
    "disable_transport": number;
    "po_cc_control": number;
    "volca_fm_velocity": number;
    "volca_fm_midi_ch_1": number;
    "volca_fm_midi_ch_2": number;
    "sync_out_enabled": number;
    "midi_ppqn": number;
    "midi_note_record_1": number;
    "midi_note_record_2": number;
    "midi_note_record_3": number;
    "midi_note_record_4": number;
    "midi_note_record_5": number;
    "midi_note_record_6": number;
    "midi_note_record_7": number;
    "midi_note_record_8": number;
    "midi_note_record_9": number;
    "midi_note_record_10": number;
    "midi_note_record_11": number;
    "midi_note_record_12": number;
    "midi_note_record_13": number;
    "midi_note_record_14": number;
    "midi_note_record_15": number;
    "midi_note_record_16": number;
    "looper_enabled": number;
    "looper_autoplay_after_record": number;
    "looper_transport_control_link": number;
    "midi_note_loop_start_stop": number;
    "midi_note_loop_clear": number;
    "looper_quantized": number;
    "ble_midi_enabled": number;
}