import Ajv, {JSONSchemaType} from "ajv"
const ajv = new Ajv()
import { configInterface } from './default.js';



const schema: JSONSchemaType<configInterface> = {
    type: "object",
    properties: {
      midi_note_1: { type: "integer" },
      midi_note_2: { type: "integer" },
      midi_note_3: { type: "integer" },
      midi_note_4: { type: "integer" },
      midi_note_5: { type: "integer" },
      midi_note_6: { type: "integer" },
      midi_note_7: { type: "integer" },
      midi_note_8: { type: "integer" },
      midi_note_9: { type: "integer" },
      midi_note_10: { type: "integer" },
      midi_note_11: { type: "integer" },
      midi_note_12: { type: "integer" },
      midi_note_13: { type: "integer" },
      midi_note_14: { type: "integer" },
      midi_note_15: { type: "integer" },
      midi_note_16: { type: "integer" },
      midi_note_sound: { type: "integer" },
      midi_note_pattern: { type: "integer" },
      midi_note_bpm: { type: "integer" },
      midi_note_special: { type: "integer" },
      midi_note_fx: { type: "integer" },
      midi_note_play: { type: "integer" },
      midi_note_write: { type: "integer" },
      po_midi_channel: { type: "integer" },
      disable_transport: { type: "integer" },
      po_cc_control: { type: "integer" },
      volca_fm_velocity: { type: "integer" },
      volca_fm_midi_ch_1: { type: "integer" },
      volca_fm_midi_ch_2: { type: "integer" },
      sync_out_enabled: { type: "integer" },
      midi_ppqn: { type: "integer" },
      midi_note_record_1: { type: "integer" },
      midi_note_record_2: { type: "integer" },
      midi_note_record_3: { type: "integer" },
      midi_note_record_4: { type: "integer" },
      midi_note_record_5: { type: "integer" },
      midi_note_record_6: { type: "integer" },
      midi_note_record_7: { type: "integer" },
      midi_note_record_8: { type: "integer" },
      midi_note_record_9: { type: "integer" },
      midi_note_record_10: { type: "integer" },
      midi_note_record_11: { type: "integer" },
      midi_note_record_12: { type: "integer" },
      midi_note_record_13: { type: "integer" },
      midi_note_record_14: { type: "integer" },
      midi_note_record_15: { type: "integer" },
      midi_note_record_16: { type: "integer" },
      looper_enabled: { type: "integer" },
      looper_autoplay_after_record: { type: "integer" },
      looper_transport_control_link: { type: "integer" },
      midi_note_loop_start_stop: { type: "integer" },
      midi_note_loop_clear: { type: "integer" },
      looper_quantized: { type: "integer" },
      ble_midi_enabled: { type: "integer" }
    },
    required: [
        "midi_note_1",
        "midi_note_2",
        "midi_note_3",
        "midi_note_4",
        "midi_note_5",
        "midi_note_6",
        "midi_note_7",
        "midi_note_8",
        "midi_note_9",
        "midi_note_10",
        "midi_note_11",
        "midi_note_12",
        "midi_note_13",
        "midi_note_14",
        "midi_note_15",
        "midi_note_16",
        "midi_note_sound",
        "midi_note_pattern",
        "midi_note_bpm",
        "midi_note_special",
        "midi_note_fx",
        "midi_note_play",
        "midi_note_write",
        "po_midi_channel",
        "disable_transport",
        "po_cc_control",
        "volca_fm_velocity",
        "volca_fm_midi_ch_1",
        "volca_fm_midi_ch_2",
        "sync_out_enabled",
        "midi_ppqn",
        "midi_note_record_1",
        "midi_note_record_2",
        "midi_note_record_3",
        "midi_note_record_4",
        "midi_note_record_5",
        "midi_note_record_6",
        "midi_note_record_7",
        "midi_note_record_8",
        "midi_note_record_9",
        "midi_note_record_10",
        "midi_note_record_11",
        "midi_note_record_12",
        "midi_note_record_13",
        "midi_note_record_14",
        "midi_note_record_15",
        "midi_note_record_16",
        "looper_enabled",
        "looper_autoplay_after_record",
        "looper_transport_control_link",
        "midi_note_loop_start_stop",
        "midi_note_loop_clear",
        "looper_quantized",
        "ble_midi_enabled",
      // Add all other properties to the required list as needed
      // ...
    ],
    additionalProperties: true
}

export const validateConfig =ajv.compile(schema)